# Generated by Django 4.0.3 on 2022-03-18 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=10000)),
                ('option_1', models.CharField(max_length=10000)),
                ('option_2', models.CharField(max_length=10000)),
                ('option_3', models.CharField(max_length=10000)),
                ('option_4', models.CharField(max_length=10000)),
                ('option_correct', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question')),
            ],
        ),
    ]
